declare const require: any;
declare const process: any;
declare const console: any;
declare const __dirname: string;
declare const __filename: string;
declare const Buffer: any;
declare const global: any;
declare const module: any;
declare const exports: any;
